/*
 * File: app/view/PreviewWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tunes.view.PreviewWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.previewwindow',

    requires: [
        'Tunes.view.PreviewWindowViewModel',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'previewwindow'
    },
    autoShow: true,
    height: 352,
    resizable: false,
    tpl: [
        '<video autoplay preload="auto">',
        ' <source src="{preview}" type="video/mp4">',
        '</video>'
    ],
    width: 640,
    title: 'My Window',
    modal: true

});